---
name: pkgdown

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.cff'
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    concurrency:  # restrict concurrency for non-PR jobs
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup tinytex
        uses: r-lib/actions/setup-tinytex@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build docs
        run: pkgdown::build_site_github_pages(new_process=FALSE, install=FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          clean: false
          branch: gh-pages
          folder: docs
...
